name: huntndivas
description: "HuntNDivas App – Find Your Wild • Connect • Mentor • Equip"
publish_to: 'none'

version: 1.0.1+2   # <name>+<code>


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: 7.0.2
  latlong2: ^0.9.1


  # Upgrade FMTC to v10+ (compatible with flutter_map 7 + latlong2 0.9)
  flutter_map_tile_caching: 10.0.0

  geolocator: ^12.0.0




  # --- Added packages for HuntNDivas v2 ---
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/HuntNDivas_logo1.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: 0xFFF6F0EA
  color_dark: 0xFF1E1E1E
  image: assets/images/HuntNDivas_logo1.png
  android_12:
    color: 0xFFF6F0EA
    color_dark: 0xFF1E1E1E
    image: assets/images/HuntNDivas_logo1.png
  web: false



# Example for adding custom fonts later
# fonts:
#   - family: LeagueSpartan
#     fonts:
#       - asset: fonts/LeagueSpartan-Regular.ttf
#       - asset: fonts/LeagueSpartan-Bold.ttf
#         weight: 700
#   - family: Montserrat
#     fonts:
#       - asset: fonts/Montserrat-Regular.ttf
#       - asset: fonts/Montserrat-Bold.ttf
#         weight: 700
